name: test
on:
  push: {}
  workflow_dispatch: {}

jobs:
  test:
    name: RSpec
    runs-on: ubuntu-20.04
    steps:
      - name: check out
        uses: actions/checkout@v3

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: install deps
        run: bundle install

      - name: test
        run: bundle exec rake spec
